server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root  #${DEVINT_DB_PASSWORD}
    url: 'jdbc:mysql://localhost:3306/user_reg' #${DEVINT_DB_URL}
    username: root  #${DEVINT_DB_USER}

  mail:
    host: smtp.gmail.com
    port: 587
    username: "bugboard1@gmail.com"
    password: "waum rizj weod rukd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true