server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  thymeleaf:
    prefix: file:../frontend-01/src/pages
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: file:../frontend-01/public/
      add-mappings: true
  datasource:
    password: PavitraGate1@B19
    url: jdbc:mysql://127.0.0.1:3306/user_reg?reconnect=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true